-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS orders(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  uuid UUID UNIQUE NOT NULL,
  number VARCHAR UNIQUE NOT NULL,
  state VARCHAR NOT NULL,
  accrual NUMERIC DEFAULT 0 NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  uploaded_at TIMESTAMP WITH TIME ZONE NOT NULL,
  account_id NUMERIC NOT NULL,
  PRIMARY KEY(id)
);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS users;
-- +goose StatementEnd
